import type { Metadata } from "next";
import { Caprasimo, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";

const caprasimo = Caprasimo({
  variable: "--font-caprasimo",
  subsets: ["latin"],
  weight: "400",
});

const jakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${caprasimo.variable} ${jakarta.variable} antialiased bg-white`}
      >
        <main className="min-h-screen overflow-hidden">
          <div className="mx-auto max-w-[1024px] pb-[83px] bg-white">
            {children}
          </div>

          <Footer />
        </main>
      </body>
    </html>
  );
}
