import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Bring This Food",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className="min-h-screen overflow-hidden bg-white">
        <div className="mx-auto max-w-[1024px] pb-[83px] bg-white">
          {children}
        </div>
        <Toaster richColors />
        <Footer />
      </main>
    </>
  );
}
